export const SET_REGISTER = "SET_REGISTER";
export const USER_DASHBOARD = "USER_DASHBOARD";
export const GET_PROFILE = "GET_PROFILE";
export const SET_REGISTER_COUNTRY = "SET_REGISTER_COUNTRY";
export const SET_REGISTER_STATE = "SET_REGISTER_STATE";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_REGISTER_COUNTRY_NEW = "SET_REGISTER_COUNTRY_NEW";
